services:
  - type: web
    name: agenda-contactos
    env: docker
    repo: https://github.com/vcruz09/Agenda-de-contactos
    branch: main
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: dpg-d0ilcbbe5dus739nrh40-a.oregon-postgres.render.com
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: agendacontacto
      - key: DB_USERNAME
        value: vane
      - key: DB_PASSWORD
        value: VrNMZnrkPtGgx4vYx4j2P4I8B2Dad6to
      - key: APP_URL
        value: https://tu-app-en-render.onrender.com
      - key: SESSION_DRIVER
        value: file
      - key: QUEUE_CONNECTION
        value: sync
      - key: FILESYSTEM_DISK
        value: local
