services:
  - type: web
    name: agenda-contactos
    env: php
    region: oregon
    plan: free
    repo: https://github.com/vcruz09/Agenda-de-contactos
    branch: main
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan config:clear
      php artisan key:generate
      php artisan migrate --force
      php artisan storage:link
    startCommand: php artisan serve --host 0.0.0.0 --port $PORT
    envVars:
      - key: APP_ENV
        value: production

      - key: APP_KEY
        generateValue: true

      - key: APP_URL
        value: http://localhost

      - key: DB_CONNECTION
        value: mysql

      - key: DB_HOST
        value: YOUR_MYSQL_HOST

      - key: DB_PORT
        value: 3306

      - key: DB_DATABASE
        value: YOUR_DATABASE_NAME

      - key: DB_USERNAME
        value: YOUR_DB_USER

      - key: DB_PASSWORD
        value: YOUR_DB_PASSWORD

      - key: SESSION_DRIVER
        value: cookie

      - key: CACHE_DRIVER
        value: file

      - key: QUEUE_CONNECTION
        value: sync

      - key: FILESYSTEM_DISK
        value: local
